name: Tests

on:
  push:
    branches:
      - main  # Change this to your main branch name
      
permissions:
  contents: read
  
env:
  TOKEN : ${{ secrets.TOKEN }}
  
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Java
      run: |
        sudo apt-get update && sudo apt-get install -y default-jdk
        java -version

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9  # Change this to your desired Python version

    - name: Install dependencies
      run: |
        # pip install -r requirements.txt
        cd Lava
        wget https://github.com/lavalink-devs/Lavalink/releases/download/3.7.11/Lavalink.jar
        cd plugins && wget https://github.com/topi314/LavaSrc/releases/download/3.2.9/lavasrc-plugin-3.2.9.jar && cd ../
        java -jar Lavalink.jar
      working-directory: ./  # Change this to your project's root directory

    - name: Deploy
      run: |
        python --version
        # Add any deployment commands here
        # For example, to run your Python application:
        # python src/app.py
        # python src/main.py
